### ISSUE TITLE
Не работает перемещение по карте.

### ISSUE THREAD

**Issue by konstantinzolotarev** [wmlabtx/abclient#1]
Версия: 2.33.0
Клиент не ходит и постоянно ждет ответа от НЛ сервера.

**Comment by wmlabtx** [comment]
Идет подготовка 2.34, с маскировкой следилки и запросами БД.

**Comment by smokefrhell** [comment]
А можно ссылку на клиента?

**Comment by wmlabtx** [comment]
https://github.com/wmlabtx/abclient/wiki

**Comment by smokefrhell** [comment]
Ammm, who you password to rar?
